name: mad_flut_p
description: "A new Flutter project"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  fluttertoast: ^8.0.8
  shared_preferences: ^2.2.2
  flutter:
    sdk: flutter
  firebase_core: ^2.30.1
  provider: ^6.0.4
  firebase_auth: ^4.19.4
  firebase_database: ^10.5.4
  http: ^1.2.1
  geolocator: ^12.0.0
  flutter_map: ^7.0.1
  latlong2: ^0.9.0
  path_provider: ^2.0.9
  sqflite: ^2.0.0+4
  csv: ^6.0.0
  intl: ^0.19.0
  logger: ^2.2.0
  cupertino_icons: ^1.0.6
  path: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/weatherIcon.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"