// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6m4J5XcHpIQjVZ6qx9WZq73MjbwvSF00',
    appId: '1:819439870848:web:93f86a0cc7cb50f5339765',
    messagingSenderId: '819439870848',
    projectId: 'flutter-app-a9c54',
    authDomain: 'flutter-app-a9c54.firebaseapp.com',
    storageBucket: 'flutter-app-a9c54.appspot.com',
    measurementId: 'G-F6NTQ87BH7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIY_gcPsYtYAvKMADaYe0gWn0E0rF6c5g',
    appId: '1:819439870848:android:b1586d4eff277db0339765',
    messagingSenderId: '819439870848',
    projectId: 'flutter-app-a9c54',
    storageBucket: 'flutter-app-a9c54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMqYw1n03PxVURvdxD6tVV5PtVb7EH6e0',
    appId: '1:819439870848:ios:a3d9e7f7b23e8bf6339765',
    messagingSenderId: '819439870848',
    projectId: 'flutter-app-a9c54',
    storageBucket: 'flutter-app-a9c54.appspot.com',
    iosBundleId: 'com.example.madFlutp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6m4J5XcHpIQjVZ6qx9WZq73MjbwvSF00',
    appId: '1:819439870848:web:4c2a627c82c00dea339765',
    messagingSenderId: '819439870848',
    projectId: 'flutter-app-a9c54',
    authDomain: 'flutter-app-a9c54.firebaseapp.com',
    storageBucket: 'flutter-app-a9c54.appspot.com',
    measurementId: 'G-WD2ZXVLQF1',
  );
}
